### PR TITLE
Fix possible crash when URI parse fails

### LINKED ISSUE #40: Panic upon launch
macOS Sonoma, Apple M1 Silicon

```
% go install github.com/fyne-io/terminal/cmd/fyneterm@latest
```

```
* % panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x105039628]

goroutine 7 [running]:
github.com/fyne-io/terminal.(*Terminal).setDirectory(0x14000492de8?, {0x14000608b2a, 0x10})
        /Users/amanvm/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230919095627-0cfe5d6b97dc/osc.go:50 +0x48
github.com/fyne-io/terminal.(*Terminal).handleOSC(0x14000492e80?, {0x14000608b28?, 0x16?})
        /Users/amanvm/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230919095627-0cfe5d6b97dc/osc.go:24 +0x164
github.com/fyne-io/terminal.(*Terminal).handleOutput(0x14000428000, {0x1400070e000, 0x16, 0x150024200520018?})
        /Users/amanvm/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230919095627-0cfe5d6b97dc/output.go:111 +0x1ec
github.com/fyne-io/terminal.(*Terminal).run(0x14000428000)
        /Users/amanvm/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230919095627-0cfe5d6b97dc/term.go:261 +0x140
github.com/fyne-io/terminal.(*Terminal).RunLocalShell(0x14000428000)
        /Users/amanvm/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230919095627-0cfe5d6b97dc/term.go:278 +0x54
main.newTerminalWindow.func5()
        /Users/amanvm/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230919095627-0cfe5d6b97dc/cmd/fyneterm/main.go:133 +0x30
created by main.newTerminalWindow in goroutine 1
        /Users/amanvm/go/pkg/mod/github.com/fyne-io/terminal@v0.0.0-20230919095627-0cfe5d6b97dc/cmd/fyneterm/main.go:132 +0x6e0
```

### PR DESCRIPTION
**Pull request by andydotxyz**
Finally tracked down what could have caused the macOS reports

Fixes #40

### CODE REVIEW

File: osc.go [hunk 1]
```diff
@@ -31,7 +31,7 @@ func (t *Terminal) handleOSC(code string) {
 
 func (t *Terminal) setDirectory(uri string) {
 	u, err := storage.ParseURI(uri)
-	if err == nil {
+	if err != nil {
 		// working around a Fyne bug where file URI does not parse host
```
Comment (Jacalz) [inline osc.go:35]: Is there an upstream bug tracking this?

Comment (andydotxyz) [reply osc.go:35]: I'm not sure if it is still an issue or what the details are - it was so long ago.
But it doesn't relate to this fix ironically - the issue here was that it was using the url when the parse failed instead of when it succeeded...

**Comment by andydotxyz** [comment]
No objections in a week...
