### PR TITLE
Fix confusion with paste buffers and keyboard shortcuts

### LINKED ISSUE #134: "Shift + Insert" produces "^V" instead of correct keys in TermGrid key handling
# Issue

When trying to register a shortcut to handle "Shift + Insert", it's not possible to detect as the actual input that Fyne appears to receive is "^V" rather than actual keys.

When pressing the Shift key, I correctly log "Shift". When pressing the Insert key I correctly log "Insert". Press them together, "Shift" is detected, "Insert" is not and `*fyne.ShortcutPaste &{Clipboard:{}}` is produced in `TypedShortcut`, which is no as terminal application do need to know the difference between "Control + V" and "Shift + Insert", since most do not actually expect "Control + V" as as a sequence for pasting.

TL;DR; typed keys should be represented correctly in Fyne applications.

(I'd be happy to be told I've missed something obvious and this behaviour can be fixed/changes easily!)

# Details

```
Fyne    2.6.1
Windows 11
Go      1.25.2
```

### PR DESCRIPTION
**Pull request by andydotxyz**
Fixes #134

### CODE REVIEW

File: input.go [hunk 1]
```diff
@@ -188,26 +188,35 @@ func (t *Terminal) TypedShortcut(s fyne.Shortcut) {
...
-			_, _ = t.in.Write([]byte{0x18})
-
-		} else if _, ok := s.(*fyne.ShortcutCopy); ok {
-			_, _ = t.in.Write([]byte{0x3})
-
-		} else if _, ok := s.(*fyne.ShortcutPaste); ok {
-			_, _ = t.in.Write([]byte{0x16})
-
+		if ct, ok := s.(*fyne.ShortcutCut); ok {
+			if ct.Secondary {
```
Comment (drunlade) [inline input.go]: Perhaps you could have exposed the triggering keys/key-code on the shortcut struct along side the `Secondary` bool? This would fix your issue here of trying to determine what keys to translate them into here; you could just write whatever key-code was originally captured when converting the input into a shortcut. The added bonus being that developers like my self would then be able to tell the exact keys used to trigger the shortcut and add custom handling if we choose to do so.
